version: "3.5"
services:
  app:
    volumes:
      - ../tw-app:/app
      - /app/node_modules
  server:
    volumes:
      - ../tw-server:/app
      - /app/node_modules
  data:
    volumes:
      - ../tw-data:/app
      - ../tw-server/src/generated:/app/generated
      - /app/node_modules
