version: "3.5"
services:
  server:
    volumes:
      - ../tw-server:/app
      - graphql-types:/app/src/generated
      - /app/node_modules
  data:
    volumes:
      - ../tw-data:/app
      - graphql-types:/app/generated
      - /app/node_modules
